car_appointment/car_appointment/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('repair_appointment.urls')),
]

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += [
#         # /__debug__/
#         path('__debug__/', include(debug_toolbar.urls)),
#     ]

car_appointment/repair_appointment/urls.py
from django.urls import path
from . import views

app_name = 'repair_appointment'
urlpatterns = [
    # /
    path('', views.RequestActivationView.as_view(), name='request_activation'),

    # /activation-requested/
    path('activation-requested/', views.request_activation_confirmed_view, name='request_activation_confirmed'),

    # /appointment-requested/
    path('appointment-requested/<uuid:uid>/', views.RequestAppointmentView.as_view(), name='request_appointment'),

    #/appointment-confirmed/
    path('appointment-confirmed/', views.request_appointment_confirmed_view, name='request_appointment_confirmed'),
]

car_appointment/repair_appointment/models.py
import uuid
from django.db import models
from django.core.validators import RegexValidator
from datetime import datetime, timezone
import pytz


class AppointmentUser(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    first_name = models.CharField(max_length=70)
    last_name = models.CharField(max_length=70)
    phone_regex = RegexValidator(regex=r'^\+\d{8,15}$', message="Phone number must be entered in the format: '+999999999'. Minimum length 8 and up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=16)
    email_address = models.EmailField()
    is_activated = models.BooleanField(default=False)


class AppointmentRequest(models.Model):
    appointment_user = models.ForeignKey(AppointmentUser, on_delete=models.CASCADE)
    vehicle_repair = models.TextField()
    appointment_time = models.DateTimeField()

    # def save(self, *args, **kwargs):
    #     if not self.id:
    #         local_timestamp = datetime.timestamp(self.appointment_time)
    #         utc_dt = datetime.fromtimestamp(local_timestamp, pytz.utc)
    #         self.appointment_time = utc_dt
    #         # self.appointment_time = self.appointment_time.astimezone().astimezone(pytz.utc).replace(tzinfo=None)
    #
    #     super(AppointmentRequest, self).save(*args, **kwargs)


class Vehicle(models.Model):
    appointment_user = models.ForeignKey(AppointmentUser, on_delete=models.CASCADE)
    vehicle_year = models.CharField(max_length=20)
    vehicle_model = models.CharField(max_length=20)
    vehicle_make = models.CharField(max_length=20, default='')

car_appointment/repair_appointment/forms.py
from django import forms
from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.utils import timezone
from django.template.loader import render_to_string
from bootstrap_datepicker_plus import DateTimePickerInput
from . import models


class RequestActivationForm(forms.ModelForm):
    class Meta:
        model = models.AppointmentUser
        fields = ('email_address',)

    error_css_class = 'error'
    required_css_class = 'required'

    def send_email(self, context):
        user = context['user_id']
        subject = 'Car Repair Appointment Activation Email'
        email_body = render_to_string('repair_appointment/activation_email.html', context)
        email_from = 'walkersorlie@gmail.com'
        recipient_list = [self.cleaned_data['email_address']]
        send_mail(subject, email_body, email_from, recipient_list)


class AppointmentUserForm(forms.ModelForm):
    class Meta:
        model = models.AppointmentUser
        fields = ('first_name', 'last_name', 'phone_number')


class RequestAppointmentForm(forms.ModelForm):
    class Meta:
        model = models.AppointmentRequest
        fields = ('vehicle_repair', 'appointment_time')
        widgets = {
            'appointment_time': DateTimePickerInput(),
        }


    error_css_class = 'error'
    required_css_class = 'required'

    def clean_appointment_time(self):
        local_dt = self.cleaned_data['appointment_time']
        if local_dt <= timezone.now():
            raise forms.ValidationError("Please select an appointment in the future")
        return local_dt



class VehicleForm(forms.ModelForm):
    class Meta:
        model = models.Vehicle
        fields = ('vehicle_year', 'vehicle_make', 'vehicle_model')

    error_css_class = 'error'
    required_css_class = 'required'

car_appointment/repair_appointment/views.py
import uuid
import datetime
from . import forms
from . import models
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.edit import FormView, CreateView
from django.template.loader import render_to_string


class RequestActivationView(CreateView):
    template_name = 'repair_appointment/request_activation.html'
    form_class = forms.RequestActivationForm
    model = models.AppointmentUser
    success_url = reverse_lazy('repair_appointment:request_activation_confirmed')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.first_name = ''
        user.last_name = ''
        user.phone_number = ''
        user.email = form.cleaned_data['email_address']

        user.save()
        context = {
            'user_id': user.id,
            'protocol': self.request.scheme,
            'domain': self.request.get_host
        }
        form.send_email(context)

        return super().form_valid(form)



class RequestAppointmentView(TemplateView):
    template_name = 'repair_appointment/request_appointment.html'

    def get_context_data(self, **kwargs):
        context = super(RequestAppointmentView, self).get_context_data(**kwargs)
        user = models.AppointmentUser.objects.get(pk=self.kwargs['uid'])
        user_forms_data = {}
        if user.is_activated:
            user_forms_data = {
                'first_name': user.first_name,
                'last_name': user.last_name,
                'phone_number': user.phone_number
            }
            user_form = forms.AppointmentUserForm(initial=user_forms_data, prefix='user_form')

            appointment_instance = user.appointmentrequest_set.order_by('pk')[0]
            appointment_form_data = {
                'vehicle_repair': appointment_instance.vehicle_repair,
                'appointment_time': appointment_instance.appointment_time
            }
            appointment_form = forms.RequestAppointmentForm(initial=appointment_form_data, prefix='appointment_form')

            vehicle_instance = user.vehicle_set.order_by('pk')[0]
            vehicle_form_data = {
                'vehicle_year': vehicle_instance.vehicle_year,
                'vehicle_make': vehicle_instance.vehicle_make,
                'vehicle_model': vehicle_instance.vehicle_model
            }
            vehicle_form = forms.VehicleForm(initial=vehicle_form_data, prefix='vehicle_form')

            context['is_activated'] = True
        else:
            user_form = forms.AppointmentUserForm(prefix='user_form')
            appointment_form = forms.RequestAppointmentForm(prefix='appointment_form')
            vehicle_form = forms.VehicleForm(prefix='vehicle_form')

        context['user_form'] = user_form
        context['user_forms_data'] = user_forms_data
        context['appointment_form'] = appointment_form
        context['vehicle_form'] = vehicle_form
        context['id'] = self.kwargs['uid']

        return context

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.get_context_data(**kwargs))

    def post(self, request, *args, **kwargs):
        user_form = forms.AppointmentUserForm(self.request.POST, prefix='user_form')
        appointment_form = forms.RequestAppointmentForm(self.request.POST, prefix='appointment_form')
        vehicle_form = vehicle_form = forms.VehicleForm(self.request.POST, prefix='vehicle_form')

        if user_form.is_valid() and appointment_form.is_valid() and vehicle_form.is_valid():
            user_instance = get_object_or_404(models.AppointmentUser, pk=self.kwargs['uid'])
            user_instance.first_name = user_form.cleaned_data['first_name']
            user_instance.last_name = user_form.cleaned_data['last_name']
            user_instance.phone_number = user_form.cleaned_data['phone_number']
            user_instance.is_activated = True
            user_instance.save()

            appointment_request_instance = models.AppointmentRequest(appointment_user=user_instance, vehicle_repair=appointment_form.cleaned_data['vehicle_repair'], appointment_time=appointment_form.cleaned_data['appointment_time'])
            appointment_request_instance.save()

            vehicle_instance = models.Vehicle(appointment_user=user_instance, vehicle_year=vehicle_form.cleaned_data['vehicle_year'], vehicle_model=vehicle_form.cleaned_data['vehicle_model'], vehicle_make=vehicle_form.cleaned_data['vehicle_make'])
            vehicle_instance.save()

            to_user_email_context = {
                'appointment': appointment_request_instance,
                'email': user_instance.email_address,
            }
            subject = 'Car Repair Appointment Confirmation'
            email_body = render_to_string('repair_appointment/user_request_appointment_confirmed_email.html', to_user_email_context)
            email_from = 'walkersorlie@gmail.com'
            recipient_list = [user_instance.email_address]
            send_mail(subject, email_body, email_from, recipient_list)

            internal_confirmation_email_context = {
                'user': user_instance,
                'appointment': appointment_request_instance,
                'vehicle': vehicle_instance,
                'ip_address': request.META['REMOTE_ADDR'],
            }
            email_body = render_to_string('repair_appointment/internal_appointment_request_confirm_email.html', internal_confirmation_email_context)
            recipient_list = ['repairs@example.com']
            send_mail(subject, email_body, email_from, recipient_list)

            return HttpResponseRedirect(reverse('repair_appointment:request_appointment_confirmed'))
        else:
            return self.form_invalid(request, user_form, appointment_form, vehicle_form, **kwargs)

    def form_invalid(self, request, user_form, appointment_form, vehicle_form, **kwargs):
        user_form.prefix = 'user_form'
        appointment_form.prefix = 'appointment_form'
        vehicle_form.prefix = 'vehicle_form'

        context = {
            'user_form': user_form,
            'appointment_form': appointment_form,
            'vehicle_form': vehicle_form,
        }

        return render(request, self.template_name, context)



def request_activation_confirmed_view(request):
    return render(request, 'repair_appointment/request_activation_confirmed.html')


def request_appointment_confirmed_view(request):
    return render(request, 'repair_appointment/request_appointment_confirmed.html')

car_appointment/repair_appointment/templates/repair_appointment/activation_email.html
{% autoescape off %}
You have requested an appointment for a vehicle repair. Please follow this link to complete your account activation and schedule an appointment.
{{ protocol }}://{{ domain }}{% url 'repair_appointment:request_appointment' uid=user_id %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
Car Repair
{% endautoescape %}

car_appointment/repair_appointment/templates/repair_appointment/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Car Repair Demo">
    <meta name="author" content="Walker Sorlie">
    <title>Car Repair Demo</title>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

    {% block extrahead %}
    {% endblock %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>
  <body>
    {% block body_content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

car_appointment/repair_appointment/templates/repair_appointment/internal_appointment_request_confirm_email.html
{% autoescape off %}
A user has requested an appointment for vehicle repairs. Here is the information:

Client
Name: {{ user.first_name }} {{ user.last_name }}
Phone Number: {{ user.phone_number}}
Email Address: {{ user.email_address }}
IP Address: {{ ip_address}}

Vehicle Information
Vehicle Year: {{ vehicle.vehicle_year }}
Vehicl Make: {{ vehicle.vehicle_make }}
Vehicle Model: {{ vehicle.vehicle_model }}

Appointment Information
Requested Repair: {{ appointment.vehicle_repair }}
Appointment Time: {{ appointment.appointment_time }}

Sincerely,
Car Repair
{% endautoescape %}

car_appointment/repair_appointment/templates/repair_appointment/request_activation.html
{% extends "repair_appointment/base.html" %}
  {% block body_content %}
    {% if form.errors %}
      <div class="container">
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
      </div>
    {% endif %}

    <div class="container mt-5">
      <div class="row justify-content-center">
        <div class="col-4">
          <h3 class="mb-4">Please enter your email address to request an activation email</h3>
          <form method="post">
              {% csrf_token %}
              {{ form }}
              <input type="submit" value="Submit">
          </form>
        </div>
      </div>
    </div>
  {% endblock %}

car_appointment/repair_appointment/templates/repair_appointment/request_activation_confirmed.html
{% extends "repair_appointment/base.html" %}
  {% block body_content %}
    <div class="container mt-5">
      <div class="row justify-content-center">
        <div class="col-4">
          <h3>Activation Requested!</h3>
          <p>We have sent you an activation email</p>
        </div>
      </div>
    </div>
  {% endblock %}

car_appointment/repair_appointment/templates/repair_appointment/request_appointment.html
{% extends "repair_appointment/base.html" %}

  {% load bootstrap4 %}
  {% block extrahead %}
    {{ appointment_form.media }}
  {% endblock %}

  {% block body_content %}
    {% if user_form.errors %}
      <div class="container">
      {% for field in user_form %}
          {% for error in field.errors %}
              <div class="alert alert-danger">
                  <strong>{{ error|escape }}</strong>
              </div>
          {% endfor %}
      {% endfor %}
      {% for error in user_form.non_field_errors %}
          <div class="alert alert-danger">
              <strong>{{ error|escape }}</strong>
          </div>
      {% endfor %}
    {% endif %}
    {% if appointment_form.errors %}
      {% for field in appointment_form %}
          {% for error in field.errors %}
              <div class="alert alert-danger">
                  <strong>{{ error|escape }}</strong>
              </div>
          {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
              <strong>{{ error|escape }}</strong>
          </div>
      {% endfor %}
    {% endif %}
    {% if vehicle_form.errors %}
      {% for field in vehicle_form %}
          {% for error in field.errors %}
              <div class="alert alert-danger">
                  <strong>{{ error|escape }}</strong>
              </div>
          {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
              <strong>{{ error|escape }}</strong>
          </div>
      {% endfor %}
    {% endif %}
    </div>

    <div class="container mt-5 mb-4">
      <div class="row justify-content-center mb-5">
        <h2>Request an Appointment</h2>
      </div>
      {% if is_activated %}
        <div class="row justify-content-center mb-5">
          <div class="col-6">
              <h3>It looks like you've already requested an appointment. Please rate us on a scale from 1-5:</h3>
              <div class="container">
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">
                  <label class="form-check-label" for="inlineRadio1">1</label>
                </div>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2">
                  <label class="form-check-label" for="inlineRadio2">2</label>
                </div>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option3">
                  <label class="form-check-label" for="inlineRadio3">3</label>
                </div>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio4" value="option4">
                  <label class="form-check-label" for="inlineRadio3">4</label>
                </div>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio5" value="option5">
                  <label class="form-check-label" for="inlineRadio3">5</label>
                </div>
              </div>
          </div>
        </div>
      {% endif %}
      <div class="row justify-content-center"
        <div class="col-10">
          <form method="post">
            {% csrf_token %}
            {% bootstrap_form user_form %}
            {% bootstrap_form vehicle_form %}

            {% bootstrap_form appointment_form %}
            {% if not is_activated %}
              <input type="submit" value="Submit">
            {% endif %}
          </form>
        </div>
      </div>
    </div>
  {% endblock %}

car_appointment/repair_appointment/templates/repair_appointment/request_appointment_confirmed.html
{% extends "repair_appointment/base.html" %}
  {% block body_content %}
    <div class="container mt-5">
      <div class="row justify-content-center">
        <div class="col-4">
          <h2>Appointment Confirmed!</h2>
          <p>We've sent you an email with the details</p>
        </div>
      </div>
    </div>
  {% endblock %}

car_appointment/repair_appointment/templates/repair_appointment/user_request_appointment_confirmed_email.html
{% autoescape off %}
Your appointment is confirmed! Here are the details:


Appointment time: {{ appointment.appointment_time}}
Repairs: {{ appointment.vehicle_repair }}

Sincerely,
Car Repair
{% endautoescape %}